name: nf-core-atacseq-1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
    - conda-forge::ncurses=5.9                 ## Documented conflict between R and SAMTools. See https://github.com/bioconda/bioconda-recipes/issues/1644
    - samtools=1.7
    - fastqc=0.11.7
    - fastq-screen=0.11.3
    - cutadapt=1.16
    - bwa=0.7.17
    - picard=2.18.7
    - bamtools=2.5.1
    - pysam=0.14.0
    - bedtools=2.27.1
    - ucsc-wigtobigwig=366
    - macs2=2.1.1.20160309
    - homer=4.9.1
    - subread=1.6.0
    - multiqc=1.5
    - r-optparse=1.4.4
    - r-ggplot2=2.2.1
    - r-reshape2=1.4.2
    - r-scales=0.4.1
    - r-rcolorbrewer=1.1_2
    - r-pheatmap=1.0.8
    - r-lattice=0.20_34
    - r-upsetr=1.3.3
    - bioconductor-deseq2=1.16.1
    - bioconductor-vsn=3.44.0
